
find_path(MYSQLCLIENT_INCLUDE_DIRS mysql_time.h PATH_SUFFIXES mysql)
find_library(MYSQLCLIENT_LIBRARIES NAMES mysqlclient mysqlclient_r)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MySqlClient DEFAULT_MSG MYSQLCLIENT_LIBRARIES MYSQLCLIENT_INCLUDE_DIRS)
mark_as_advanced(MYSQLCLIENT_LIBRARIES MYSQLCLIENT_INCLUDE_DIRS)

if(MYSQLCLIENT_FOUND AND NOT TARGET MySQL::MySQLClient)
  add_library(MySQL::MySQLClient INTERFACE IMPORTED)
  set_target_properties(MySQL::MySQLClient PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${MYSQLCLIENT_INCLUDE_DIRS}
    INTERFACE_LINK_LIBRARIES ${MYSQLCLIENT_LIBRARIES}
    INTERFACE_COMPILE_DEFINITIONS "HAVE_MYSQL=1"
  )
endif()
