#set(CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR}/application)
set(prefix ".")

if(NOT libdir)
  set(libdir ${prefix}/lib)
endif()
if(NOT bindir)
  set(bindir ${prefix})
endif()
if(NOT includedir)
  set(includedir ${prefix}/include)
endif()
if(NOT datarootdir)
  set(datarootdir ${prefix})
endif()
if(NOT datadir)
  set(datadir \${datarootdir})
endif()

list(APPEND final_message "-- PATH config --")
list(APPEND final_message "Prefix: ${prefix}")
list(APPEND final_message "Libdir: ${libdir}")
list(APPEND final_message "Bindir: ${bindir}")
list(APPEND final_message "Includedir: ${includedir}")
list(APPEND final_message "Datarootdir: ${datarootdir}")
list(APPEND final_message "Datadir: ${datadir}")
