#pragma once

#define SETTING_X "generic_setting"
#define SETTING_Y "unoverriden setting"

// Starting with GCC 5, we could use __has_include
#if defined SETTINGS_OVERRIDE
  // Header is generated by the buildsystem
  #include "settings_override.h"
#endif
